config/routes.rb
Myblog::Application.routes.draw do
  

  get "sitemap/index"

  devise_for :users

  resources :articles do
    resources :comments
  end

  root :to => "articles#index"
  

  match "/sitemap" => "sitemap#index", :as => :sitemap, :defaults => {:format => :xml}
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title, :tag_names

  has_many :comments, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings

  validates_presence_of :title, :body
  validates_uniqueness_of :title

  attr_writer :tag_names
  after_save :assign_tags

  def tag_names
  	@tag_names || tags.map(&:name).join('')
  end

  private

  def assign_tags
  	if @tag_names
  		self.tags = @tag_names.split(/\,/).map do |name|
  			Tag.find_or_create_by_name(name)
  		end
  	end
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
    authorize! :edit, @article
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    authorize! :create, @article

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    authorize! :update, @article

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    authorize! :destroy, @article
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<p>
  <b>Title:</b>
  <%= article.title %>
</p>
<p>
  <b>Body:</b>
  <%= article.body %>
</p>

<%= link_to 'Show', article %>
<% if can? :update, article %>
	<%= link_to 'Edit', edit_article_path(article) %>
<% end %>
<% if can? :delete, article %>
	<%= link_to 'Destroy', article, :confirm => 'Are you sure?', :method => :delete %>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :tag_names, "Tags" %>
    <%= f.text_field :tag_names %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<%= render @articles %>

<br />
<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div id="article-content" class="span-17">
  <div class="article_title">
  <h1><%= @article.title %></h1>
  </div>
 <div class="article_body">
    <p>By "Bob"
    on <%= @article.created_at.strftime("%B %d, %Y") %>
    </p>
    <p>
      <%= @article.body %>
    </p>
    <p>Tags:
    	<% @article.tags.each do |tag| %>
    		<%= tag.name %>
    	<% end %>
    </p>
  </div>
</div>
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>



	
</div>
<div id="comments">
<h2>Comments</h2>
  <%= render :partial => @article.comments %>
</div>




<%= form_for([@article, @article.comments.build]) do |f| %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</div>
	<p><%= f.submit %></p>
<% end %>